### PR TITLE
Addition

### PR DESCRIPTION
**Pull request by Neitsch**
Implemented addition, added creation of empty value.

### CODE REVIEW

**Review by oracleofnj — CHANGES_REQUESTED** [review]
We can't have (numeric) addition be a function call. I realize this is going to be a pain involving the creation of basic blocks and all, but we have to do this better.

I suggest the following LLVM logic:

(1) Get a "value type pair" by doing val1->type << 4 + val2->type (so for two numbers it would be 17, for two strings it would 34, if i did my hex math right)
(2) make the appropriate number of basic blocks and use the LLVM switch thing on the result of (1) to execute the appropriate one.

**Comment by Neitsch** [comment]
Would you be okay with
if flag1 == flag2 == NUMBER then LLVM addition
else C string addition

**Comment by oracleofnj** [comment]
There's three possibilities right? number/number, string/string, (illegal for +) 

given that we have the length of the strings in our string_p, i think it's almost as easy to write the string concatenation in LLVM as it is in C - we know exactly where all the bits have to go.

**Comment by Neitsch** [comment]
Will do different PR

**Pull request closed without merging**
