### PR TITLE
String concatenation

### PR DESCRIPTION
**Pull request by Neitsch**

### CODE REVIEW

**Comment by oracleofnj** [comment]
Can you merge in commits from equal_rights first? The fact that it's passing test_ref_between_globals.xtnd makes me think that some of it might be b/c of the "flags" thing.

**Comment by Neitsch** [comment]
I did remove that line. It was not passing before, because we did not have string addition for to_string(bar)+"\n"

**Review by oracleofnj — CHANGES_REQUESTED** [review]
This does not appear to be working properly unfortunately. This seg faults:

[1,1] main(args) {
  foo := printv(1,"Hello"+"World\n") -> 0;
  return foo;
}

**Comment by oracleofnj** [comment]
I added a test case file to the branch

**Comment by Neitsch** [comment]
Not sure why multiple string concatenations do not work out. Will look into it.
Can not reproduce segfault though.

**Review by oracleofnj — APPROVED** [review]

**Pull request merged**
