### PR TITLE
Lexbuf pos

### PR DESCRIPTION
**Pull request by oracleofnj**
Use built-in lexbuf.lex_curr_p to calculate syntax error location; add a couple test cases for situations that were not being handled properly.

### CODE REVIEW

**Review by ishaankolluri — APPROVED** [review]
considerably more elegant. is there a way to get this line number at a later stage in the compilation process?

**Comment by oracleofnj** [comment]
Not sure yet, I was going to look into that

**Comment by Neitsch** [comment]
My could preserve line numbers by storing them with the record. However after we apply transformations it will be harder to preserve.

**Comment by oracleofnj** [comment]
I think we'll be able to handle parsing errors (but not semantic errors)
without doing anything else fancy. Working on it, stay tuned

**Pull request merged**
