### PR TITLE
Remove debug

### PR DESCRIPTION
**Pull request by oracleofnj**
Based on new_string.

### CODE REVIEW

**Comment by oracleofnj** [comment]
Gack. Forgot to switch to a new branch. This brings in the command line arguments finally.

**Comment by Neitsch** [comment]
It would be nice to keep debug around for memory management, if we want to tackle this at all.

**Comment by oracleofnj** [comment]
Ok. I just don't want to forget and leave it in. I think I accidentally
applied args on top of that one rather than the other way around. Can you
revert it and then apply the args commit?

On Sat, Dec 17, 2016 at 8:17 AM Nigel Schuster <notifications@github.com>
wrote:

It would be nice to keep debug around for memory management, if we want to
tackle this at all.




—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/ExtendLang/Extend/pull/115#issuecomment-267762269>, or mute
the thread

**Comment by oracleofnj** [comment]
Alternatively I can put it back in like 10 mins if we need it. Very easy.

**Comment by Neitsch** [comment]
I'll fix it 😄

**Review by Neitsch — APPROVED** [review]
Feel free to merge.

**Comment by oracleofnj** [comment]
Closed for #129

**Pull request closed without merging**
