### PR TITLE
Sinner

### PR DESCRIPTION
**Pull request by Neitsch**
@oracleofnj is the use of floats okay?

### CODE REVIEW

**Comment by oracleofnj** [comment]
We shouldn't have an extra float type besides Number. Numbers should just be floats. When it comes time that we need them to be integers we're going to just truncate them to ints

**Comment by Neitsch** [comment]
@oracleofnj gotcha, will change
@kevinye1 please don't add commits to a PR, this PR contains enough changes and should not be bloated. I'll move it to a different branch and do a seperate PR

**Review by oracleofnj — CHANGES_REQUESTED** [review]
Please change "4" and any other similar magic constants for flags to a #define

**Comment by oracleofnj** [comment]
Another change requested: There is no reason to malloc a new copy of empty() every single time. It's an identical singleton

**Review by oracleofnj — APPROVED** [review]

**Comment by Neitsch** [comment]
Hmm, that is an interesting idea to use a singleton. Just have to increase and decrease the ref count correctly (once implemented).

**Comment by Neitsch** [comment]
Actually I think we can not simply use empty() as a singleton. In C code we are using it to initialize a new subrange and subsequently fill it with data. Do you think this is a bad pattern that we should change / create a separate initialization? Or is it good for now and we do not use the singleton pattern?
EDIT: It also conflicts with our immutable model

**Comment by oracleofnj** [comment]
Maybe it's just the name of the function that is bothering me as opposed to what it's doing - I think you're right that we do need to allocate a value structure, which we might as well initialize to empty, I kind of thought we were storing extra stuff in there. If it were called new_value() I probably wouldn't have noticed.

**Comment by oracleofnj** [comment]
PS We should at least think about how we are eventually going to do garbage collection. Some of the things (e.g. base ranges) will need to be reference counted; some of them should be able to be free()d by the function that receives them when it's done with them.

**Comment by oracleofnj** [comment]
I think if we're careful about it then the only things that will need to be reference counted are strings and base ranges.

**Comment by Neitsch** [comment]
Oh that's right, my bad. Obviously if we have a singleton we don't need to ref count. I'm creating a lot of helpers in our stdlib so that it will be easy to update the ref count (hopefully).

**Comment by Neitsch** [comment]
Will rename then.

**Comment by oracleofnj** [comment]
Another thought in that vein: We should make sure that we are only calling box_string once per actual string. For example if you have

foo() {
  [10,10] ret := "Hello, world!";
  return ret;
}

main(args) {
  [10,10] ret := foo();
  return print(ret) -> 0;
}

we should only be calling box_string once - not 100 times and certainly not 10,000 times. i would need to take a closer look to make sure this is what we are doing, but it is something to be mindful of.

**Comment by Neitsch** [comment]
This might be a problem, will discuss tomorrow.

**Comment by oracleofnj** [comment]
Feel free to merge whenever

**Comment by Neitsch** [comment]
Still got to rename. Will do in the afternoon.

**Pull request merged**
