### PR TITLE
Assigned contributions

### PR DESCRIPTION
**Pull request by Neitsch**
We are supposed to list contribution. I might have not accurately added you contribution everywhere, so please check. Also I skipped testcases.

### CODE REVIEW

**Review by ishaankolluri — APPROVED** [review]

**Comment by oracleofnj** [comment]
LGTM. Does my columbia.edu address need to be in .mailmap? jss2272@columbia.edu if so

**Review by oracleofnj — APPROVED** [review]
LGTM; jss2272@columbia.edu if that needs to be in .mailmap

**Comment by Neitsch** [comment]
No, .mailmap is just used to map commits from different accounts to the same person.
Waiting for Kevin to approve.

**Comment by Neitsch** [comment]
I'll go ahead and merge. @kevinye1 if you would like to do any more changes, feel free to PR.

**Pull request merged**
