### PR TITLE
Function calls work now

### PR DESCRIPTION
**Pull request by Neitsch**

### CODE REVIEW

**Comment by oracleofnj** [comment]
Are you sure you are checking the right list of function in your codegen for Ast.Call?

I think there are four categories of functions we might want to call from LLVM:

(1) Functions we built ourself like box_args, but that aren't exposed to the user
(2) Functions from C stdlib, like memcpy or printf, that we're using but that aren't exposed to the user
(3) Functions we generated code for based on the source
(4) Functions the user imported with an "extern" statement

Of those, they should only be able to call (3) or (4), not (1) or (2). But it looks like you are searching (1) and (2), unless I am reading it wrong

**Comment by oracleofnj** [comment]
P.S. My recommendation is that we build a single hashtable / stringmap of functions that the user can call that contains both (3) and (4). The only difference is that for (3), we not only declare the function in LLVM but also define it, and for (4) we just declare it and hope that it is around come link time.

Make sense?

**Comment by Neitsch** [comment]
I absolutely agree.
This code chunk
```Llvm.build_call (
   try Hashtbl.find helpers fn
   with Not_found -> (
     try Ast.StringMap.find fn build_externs
     with Not_found -> let (a,b) = Ast.StringMap.find fn build_function_names in b
   )
 ) args "" builder
```
Will look through our helper functions (2) (because printf is currently located there), then through the externs(4) and then through all defined functions (3). Obviously the order is not correct and it definitely is more efficient to build some representation that merges all items. But this can be fixed later.

**Comment by Neitsch** [comment]
So, since calling externs does not work yet, but it would really be good to have function calls going, it would be nice to merge it in in this form.

**Comment by oracleofnj** [comment]
Why not just take this opportunity to get it done the way we eventually want it? We're running out of time to fix stuff later on, and we should be getting rid of the printf()s in the sample code anyway (they should be replaced with write() per LRM).

Also I suggest renaming 
let extern_functions = Hashtbl.create 10
as
let extern_helper_functions = Hashtbl.create 10

to make it clear that that refers to category (2) and not (4).

**Comment by Neitsch** [comment]
Does anybody have an idea why it does not find `String.equal`

**Comment by Neitsch** [comment]
Turns out Travis runs Ocaml 4.02.3, while I am running 4.03.0. This version introduced String.equal. Will fix.

**Review by oracleofnj — APPROVED** [review]

**Pull request merged**
