### PR TITLE
Linker enhancement

### PR DESCRIPTION
**Pull request by Neitsch**

### CODE REVIEW

**Review by oracleofnj — CHANGES_REQUESTED** [review]
I think this:
rl.rlim_max = kStackSize;

is supposed to be:
rl.rlim_cur = rl.rlim_max;

I think the idea is that unless you're root you can't change rlim_max.

**Comment by oracleofnj** [comment]
I tried it out with this:
	result = getrlimit(RLIMIT_STACK, &rl);
	fprintf(stderr, "%llu\n", rl.rlim_cur);
	fprintf(stderr, "%llu\n", rl.rlim_max);
  rl.rlim_cur = rl.rlim_max;
  result = setrlimit(RLIMIT_STACK, &rl);
	fprintf(stderr, "%llu\n", rl.rlim_cur);
	fprintf(stderr, "%llu\n", rl.rlim_max);
	result = getrlimit(RLIMIT_STACK, &rl);
	fprintf(stderr, "%llu\n", rl.rlim_cur);
	fprintf(stderr, "%llu\n", rl.rlim_max);

if you do it with   rl.rlim_max = kStackSize;
then the output doesn't change between the first and second calls.

**Review by oracleofnj — APPROVED** [review]

**Comment by oracleofnj** [comment]
Wait whoops I didn't realize the other PR included this one. Please see comments above

**Comment by Neitsch** [comment]
Sorry that the commit history got messed up, was in HG mode. Should be fixed now, will merge once build passes.

**Comment by oracleofnj** [comment]
LGTM

**Pull request merged**
